[tool.poetry]
name = "agricultural-pdf-processor"
version = "0.1.0"
description = "An AI-powered Streamlit app for processing and searching agricultural PDFs using GPT-4o and sentence embeddings."
authors = ["Praneeth <apraneethkumar2k@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "exp" }]

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "^1.35.0"
openai = "^1.30.1"
sentence-transformers = "^2.6.1"
scikit-learn = "^1.5.0"
numpy = "^1.26.4"
pandas = "^2.2.2"
Pillow = "^10.3.0"
tqdm = "^4.66.4"
PyMuPDF = "^1.23.22"
python-docx = "^1.1.0"
pyngrok = "^5.3.0"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
flake8 = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
