[tool.poetry]
name = "agricultural-pdf-processor"
version = "0.1.0"
description = "An AI-powered Streamlit app for processing and searching agricultural PDFs using GPT-4o and sentence embeddings."
authors = ["Praneeth <apraneethkumar2k@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "exp" }]

[tool.poetry.dependencies]
python = "^3.8"
streamlit = "^1.32.0"
openai = "^1.12.0"
sentence-transformers = "^2.5.1"
scikit-learn = "^1.4.0"
pandas = "^2.1.0"
numpy = "^1.24.0"
python-docx = "^1.0.1"
PyMuPDF = "^1.23.8"
tqdm = "^4.66.0"
Pillow = "^10.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
